### ISSUE TITLE
Support for LIFX Z

### ISSUE THREAD

**Issue by grokdesigns** [devbobo/homebridge-lifx-lan#15]
Is there planned support for the [LIFX Z](http://www.lifx.com/products/lifx-z) light strip? It's recognized as a basic light, but none of the color options show up. I received mine and can test if needed.

**Comment by devbobo** [comment]
@grokdesigns grab the latest version, and make the following change to the `node-lifx` package to get support...
https://github.com/MariusRumpf/node-lifx/pull/43/files

I've issued a Pull Request for my change to be merged, once that is done, I'll modify my package to included the updated version.

**Comment by grokdesigns** [comment]
@devbobo I updated and made the edit you specified, but I'm not getting any color options for the LIFX Z. Also, I have strange "devices" showing up in HomeKit apps now, like [this](https://images.grokdesigns.com/images/2016/11/07/86b4d1dac79045c2cc17909f51db7fad.png).

**Comment by devbobo** [comment]
The `strange` devices.. generation 2 bulbs and above have a built-in light sensor, so that is the HomeKit service for the light sensor. If you don't want those they are easy enough to remove.
1. Download and install Hesperus from the App Store
2. Launch Hesperus
3. Click the Settings icon

![image](https://cloud.githubusercontent.com/assets/680871/20088437/279f791c-a5d4-11e6-8eea-79465926dd7c.png)
4. Select `Accessories`

![image](https://cloud.githubusercontent.com/assets/680871/20088485/68cb4ac4-a5d4-11e6-9b12-20ebddd8d401.png)
5. Swipe left on `Homebridge`

![image](https://cloud.githubusercontent.com/assets/680871/20088519/9a118792-a5d4-11e6-813e-1969f6e602f5.png)
6. Select `Config`

![image](https://cloud.githubusercontent.com/assets/680871/20088671/d97c1d38-a5d5-11e6-8630-bc48aa81bf62.png)
7. Select `Manage Platform`

![image](https://cloud.githubusercontent.com/assets/680871/20088710/159e2f9a-a5d6-11e6-8550-f784ecbb7a5a.png)
8. Select `LifxLan`

![image](https://cloud.githubusercontent.com/assets/680871/20088872/2487ba84-a5d7-11e6-8b64-00b3265ced2b.png)
9. Select `Modify Accessory`

![image](https://cloud.githubusercontent.com/assets/680871/20088887/52484b64-a5d7-11e6-81cb-a4c738a9b241.png)
10. Select the accessory to modify

![image](https://cloud.githubusercontent.com/assets/680871/20088903/71049990-a5d7-11e6-8c18-623d22f87a78.png)
11. Select `Add Characteristic`

![image](https://cloud.githubusercontent.com/assets/680871/20088931/9fe81a3e-a5d7-11e6-8047-e090b47c5834.png)
12. Select Characteristics to add and then click `Next`

![image](https://cloud.githubusercontent.com/assets/680871/20088947/c4da8228-a5d7-11e6-91ce-abcf5201eb7f.png)
8. Select `Cancel` to finish

![image](https://cloud.githubusercontent.com/assets/680871/20088967/e383a10a-a5d7-11e6-966e-605ba40250ea.png)

To remove the `Light Sensor` if you don't want it select `Remove Service` from the screen in `Step 11`.

Let me know if you have any questions.

**Comment by serhiy79** [comment]
Hi devbobo. I tried to add characteristic(saturation) to Lifx (3 generation), but i don't have option "Add characteristic" on step 11. I just can remove characteristic or service. Could you help me please?

**Comment by devbobo** [comment]
this should be resolved in `version 0.1.8`, which is live now

**Comment by devbobo** [comment]
@serhiy79 try again with the new version

**Comment by serhiy79** [comment]
I manually add lines from pull request and everything works fine. 

Sincerely,
Serhiy Shakhurdin
